# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnbuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnbuscar.setGeometry(QtCore.QRect(500, 60, 101, 31))
        self.btnbuscar.setAutoFillBackground(False)
        self.btnbuscar.setObjectName("btnbuscar")
        self.txtbusca = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbusca.setGeometry(QtCore.QRect(120, 30, 371, 41))
        self.txtbusca.setObjectName("txtbusca")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 41))
        self.label.setObjectName("label")
        self.lblresult = QtWidgets.QLabel(self.centralwidget)
        self.lblresult.setGeometry(QtCore.QRect(20, 120, 731, 451))
        self.lblresult.setObjectName("lblresult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DeezerApi"))
        self.btnbuscar.setText(_translate("MainWindow", "Buscar"))
        self.label.setText(_translate("MainWindow", "Digite o nome do artista:"))
        self.lblresult.setText(_translate("MainWindow", "Resultado"))
